// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.6.1
// source: proto/GoArm.proto

package GoArm

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type In struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Number int32 `protobuf:"varint,2,opt,name=number,proto3" json:"number,omitempty"`
}

func (x *In) Reset() {
	*x = In{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_GoArm_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *In) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*In) ProtoMessage() {}

func (x *In) ProtoReflect() protoreflect.Message {
	mi := &file_proto_GoArm_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use In.ProtoReflect.Descriptor instead.
func (*In) Descriptor() ([]byte, []int) {
	return file_proto_GoArm_proto_rawDescGZIP(), []int{0}
}

func (x *In) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *In) GetNumber() int32 {
	if x != nil {
		return x.Number
	}
	return 0
}

type Out struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Number int32 `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
}

func (x *Out) Reset() {
	*x = Out{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_GoArm_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Out) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Out) ProtoMessage() {}

func (x *Out) ProtoReflect() protoreflect.Message {
	mi := &file_proto_GoArm_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Out.ProtoReflect.Descriptor instead.
func (*Out) Descriptor() ([]byte, []int) {
	return file_proto_GoArm_proto_rawDescGZIP(), []int{1}
}

func (x *Out) GetNumber() int32 {
	if x != nil {
		return x.Number
	}
	return 0
}

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_GoArm_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_GoArm_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_GoArm_proto_rawDescGZIP(), []int{2}
}

var File_proto_GoArm_proto protoreflect.FileDescriptor

var file_proto_GoArm_proto_rawDesc = []byte{
	0x0a, 0x11, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x47, 0x6f, 0x41, 0x72, 0x6d, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x05, 0x47, 0x6f, 0x41, 0x72, 0x6d, 0x22, 0x2c, 0x0a, 0x02, 0x49, 0x6e,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x16, 0x0a, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x22, 0x1d, 0x0a, 0x03, 0x4f, 0x75, 0x74, 0x12,
	0x16, 0x0a, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x22, 0x07, 0x0a, 0x05, 0x45, 0x6d, 0x70, 0x74, 0x79,
	0x32, 0x50, 0x0a, 0x03, 0x41, 0x72, 0x6d, 0x12, 0x23, 0x0a, 0x06, 0x53, 0x65, 0x74, 0x4e, 0x75,
	0x6d, 0x12, 0x09, 0x2e, 0x47, 0x6f, 0x41, 0x72, 0x6d, 0x2e, 0x49, 0x6e, 0x1a, 0x0c, 0x2e, 0x47,
	0x6f, 0x41, 0x72, 0x6d, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x24, 0x0a, 0x06,
	0x47, 0x65, 0x74, 0x4e, 0x75, 0x6d, 0x12, 0x0c, 0x2e, 0x47, 0x6f, 0x41, 0x72, 0x6d, 0x2e, 0x45,
	0x6d, 0x70, 0x74, 0x79, 0x1a, 0x0a, 0x2e, 0x47, 0x6f, 0x41, 0x72, 0x6d, 0x2e, 0x4f, 0x75, 0x74,
	0x22, 0x00, 0x42, 0x24, 0x5a, 0x22, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x47, 0x6f, 0x41, 0x72, 0x6d, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x47, 0x6f, 0x41,
	0x72, 0x6d, 0x3b, 0x47, 0x6f, 0x41, 0x72, 0x6d, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_GoArm_proto_rawDescOnce sync.Once
	file_proto_GoArm_proto_rawDescData = file_proto_GoArm_proto_rawDesc
)

func file_proto_GoArm_proto_rawDescGZIP() []byte {
	file_proto_GoArm_proto_rawDescOnce.Do(func() {
		file_proto_GoArm_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_GoArm_proto_rawDescData)
	})
	return file_proto_GoArm_proto_rawDescData
}

var file_proto_GoArm_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_GoArm_proto_goTypes = []interface{}{
	(*In)(nil),    // 0: GoArm.In
	(*Out)(nil),   // 1: GoArm.Out
	(*Empty)(nil), // 2: GoArm.Empty
}
var file_proto_GoArm_proto_depIdxs = []int32{
	0, // 0: GoArm.Arm.SetNum:input_type -> GoArm.In
	2, // 1: GoArm.Arm.GetNum:input_type -> GoArm.Empty
	2, // 2: GoArm.Arm.SetNum:output_type -> GoArm.Empty
	1, // 3: GoArm.Arm.GetNum:output_type -> GoArm.Out
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_GoArm_proto_init() }
func file_proto_GoArm_proto_init() {
	if File_proto_GoArm_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_GoArm_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*In); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_GoArm_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Out); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_GoArm_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_GoArm_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_GoArm_proto_goTypes,
		DependencyIndexes: file_proto_GoArm_proto_depIdxs,
		MessageInfos:      file_proto_GoArm_proto_msgTypes,
	}.Build()
	File_proto_GoArm_proto = out.File
	file_proto_GoArm_proto_rawDesc = nil
	file_proto_GoArm_proto_goTypes = nil
	file_proto_GoArm_proto_depIdxs = nil
}
