// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.6.1
// source: proto/GoPrm.proto

package GoPrm

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Primary struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *Primary) Reset() {
	*x = Primary{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_GoPrm_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Primary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Primary) ProtoMessage() {}

func (x *Primary) ProtoReflect() protoreflect.Message {
	mi := &file_proto_GoPrm_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Primary.ProtoReflect.Descriptor instead.
func (*Primary) Descriptor() ([]byte, []int) {
	return file_proto_GoPrm_proto_rawDescGZIP(), []int{0}
}

func (x *Primary) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type Task struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Query   int32 `protobuf:"varint,2,opt,name=query,proto3" json:"query,omitempty"`
	Lamport int64 `protobuf:"varint,3,opt,name=lamport,proto3" json:"lamport,omitempty"`
}

func (x *Task) Reset() {
	*x = Task{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_GoPrm_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_proto_GoPrm_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_proto_GoPrm_proto_rawDescGZIP(), []int{1}
}

func (x *Task) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Task) GetQuery() int32 {
	if x != nil {
		return x.Query
	}
	return 0
}

func (x *Task) GetLamport() int64 {
	if x != nil {
		return x.Lamport
	}
	return 0
}

type Value struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Query int32 `protobuf:"varint,1,opt,name=query,proto3" json:"query,omitempty"`
}

func (x *Value) Reset() {
	*x = Value{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_GoPrm_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Value) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Value) ProtoMessage() {}

func (x *Value) ProtoReflect() protoreflect.Message {
	mi := &file_proto_GoPrm_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Value.ProtoReflect.Descriptor instead.
func (*Value) Descriptor() ([]byte, []int) {
	return file_proto_GoPrm_proto_rawDescGZIP(), []int{2}
}

func (x *Value) GetQuery() int32 {
	if x != nil {
		return x.Query
	}
	return 0
}

type Log struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Log map[int32]int32 `protobuf:"bytes,1,rep,name=log,proto3" json:"log,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
}

func (x *Log) Reset() {
	*x = Log{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_GoPrm_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Log) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Log) ProtoMessage() {}

func (x *Log) ProtoReflect() protoreflect.Message {
	mi := &file_proto_GoPrm_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Log.ProtoReflect.Descriptor instead.
func (*Log) Descriptor() ([]byte, []int) {
	return file_proto_GoPrm_proto_rawDescGZIP(), []int{3}
}

func (x *Log) GetLog() map[int32]int32 {
	if x != nil {
		return x.Log
	}
	return nil
}

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_GoPrm_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_GoPrm_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_GoPrm_proto_rawDescGZIP(), []int{4}
}

var File_proto_GoPrm_proto protoreflect.FileDescriptor

var file_proto_GoPrm_proto_rawDesc = []byte{
	0x0a, 0x11, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x47, 0x6f, 0x50, 0x72, 0x6d, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x05, 0x47, 0x6f, 0x50, 0x72, 0x6d, 0x22, 0x19, 0x0a, 0x07, 0x50, 0x72,
	0x69, 0x6d, 0x61, 0x72, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x02, 0x69, 0x64, 0x22, 0x46, 0x0a, 0x04, 0x54, 0x61, 0x73, 0x6b, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a,
	0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x71, 0x75,
	0x65, 0x72, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x6c, 0x61, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x6c, 0x61, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x22, 0x1d, 0x0a,
	0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x22, 0x64, 0x0a, 0x03,
	0x4c, 0x6f, 0x67, 0x12, 0x25, 0x0a, 0x03, 0x6c, 0x6f, 0x67, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x13, 0x2e, 0x47, 0x6f, 0x50, 0x72, 0x6d, 0x2e, 0x4c, 0x6f, 0x67, 0x2e, 0x4c, 0x6f, 0x67,
	0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x03, 0x6c, 0x6f, 0x67, 0x1a, 0x36, 0x0a, 0x08, 0x4c, 0x6f,
	0x67, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02,
	0x38, 0x01, 0x22, 0x07, 0x0a, 0x05, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x32, 0xd0, 0x01, 0x0a, 0x03,
	0x50, 0x72, 0x6d, 0x12, 0x24, 0x0a, 0x05, 0x45, 0x6c, 0x65, 0x63, 0x74, 0x12, 0x0b, 0x2e, 0x47,
	0x6f, 0x50, 0x72, 0x6d, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x1a, 0x0c, 0x2e, 0x47, 0x6f, 0x50, 0x72,
	0x6d, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x2c, 0x0a, 0x0a, 0x47, 0x65, 0x74,
	0x50, 0x72, 0x69, 0x6d, 0x61, 0x72, 0x79, 0x12, 0x0c, 0x2e, 0x47, 0x6f, 0x50, 0x72, 0x6d, 0x2e,
	0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x0e, 0x2e, 0x47, 0x6f, 0x50, 0x72, 0x6d, 0x2e, 0x50, 0x72,
	0x69, 0x6d, 0x61, 0x72, 0x79, 0x22, 0x00, 0x12, 0x26, 0x0a, 0x08, 0x43, 0x6c, 0x6f, 0x6e, 0x65,
	0x4c, 0x6f, 0x67, 0x12, 0x0a, 0x2e, 0x47, 0x6f, 0x50, 0x72, 0x6d, 0x2e, 0x4c, 0x6f, 0x67, 0x1a,
	0x0c, 0x2e, 0x47, 0x6f, 0x50, 0x72, 0x6d, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12,
	0x25, 0x0a, 0x06, 0x53, 0x65, 0x74, 0x56, 0x61, 0x6c, 0x12, 0x0b, 0x2e, 0x47, 0x6f, 0x50, 0x72,
	0x6d, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x1a, 0x0c, 0x2e, 0x47, 0x6f, 0x50, 0x72, 0x6d, 0x2e, 0x45,
	0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x26, 0x0a, 0x06, 0x47, 0x65, 0x74, 0x56, 0x61, 0x6c,
	0x12, 0x0c, 0x2e, 0x47, 0x6f, 0x50, 0x72, 0x6d, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x0c,
	0x2e, 0x47, 0x6f, 0x50, 0x72, 0x6d, 0x2e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x00, 0x42, 0x24,
	0x5a, 0x22, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x47, 0x6f, 0x41,
	0x72, 0x6d, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x47, 0x6f, 0x50, 0x72, 0x6d, 0x3b, 0x47,
	0x6f, 0x50, 0x72, 0x6d, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_GoPrm_proto_rawDescOnce sync.Once
	file_proto_GoPrm_proto_rawDescData = file_proto_GoPrm_proto_rawDesc
)

func file_proto_GoPrm_proto_rawDescGZIP() []byte {
	file_proto_GoPrm_proto_rawDescOnce.Do(func() {
		file_proto_GoPrm_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_GoPrm_proto_rawDescData)
	})
	return file_proto_GoPrm_proto_rawDescData
}

var file_proto_GoPrm_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_GoPrm_proto_goTypes = []interface{}{
	(*Primary)(nil), // 0: GoPrm.Primary
	(*Task)(nil),    // 1: GoPrm.Task
	(*Value)(nil),   // 2: GoPrm.Value
	(*Log)(nil),     // 3: GoPrm.Log
	(*Empty)(nil),   // 4: GoPrm.Empty
	nil,             // 5: GoPrm.Log.LogEntry
}
var file_proto_GoPrm_proto_depIdxs = []int32{
	5, // 0: GoPrm.Log.log:type_name -> GoPrm.Log.LogEntry
	1, // 1: GoPrm.Prm.Elect:input_type -> GoPrm.Task
	4, // 2: GoPrm.Prm.GetPrimary:input_type -> GoPrm.Empty
	3, // 3: GoPrm.Prm.CloneLog:input_type -> GoPrm.Log
	1, // 4: GoPrm.Prm.SetVal:input_type -> GoPrm.Task
	4, // 5: GoPrm.Prm.GetVal:input_type -> GoPrm.Empty
	4, // 6: GoPrm.Prm.Elect:output_type -> GoPrm.Empty
	0, // 7: GoPrm.Prm.GetPrimary:output_type -> GoPrm.Primary
	4, // 8: GoPrm.Prm.CloneLog:output_type -> GoPrm.Empty
	4, // 9: GoPrm.Prm.SetVal:output_type -> GoPrm.Empty
	2, // 10: GoPrm.Prm.GetVal:output_type -> GoPrm.Value
	6, // [6:11] is the sub-list for method output_type
	1, // [1:6] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_GoPrm_proto_init() }
func file_proto_GoPrm_proto_init() {
	if File_proto_GoPrm_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_GoPrm_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Primary); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_GoPrm_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Task); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_GoPrm_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Value); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_GoPrm_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Log); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_GoPrm_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_GoPrm_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_GoPrm_proto_goTypes,
		DependencyIndexes: file_proto_GoPrm_proto_depIdxs,
		MessageInfos:      file_proto_GoPrm_proto_msgTypes,
	}.Build()
	File_proto_GoPrm_proto = out.File
	file_proto_GoPrm_proto_rawDesc = nil
	file_proto_GoPrm_proto_goTypes = nil
	file_proto_GoPrm_proto_depIdxs = nil
}
